version: "3.8"
services:
  kibana:
    image: ${VNA_KIBANA_IMAGE}
    ports: ["${VNA_KIBANA_PORT}:5601"]
    environment:
      SERVER_NAME: vna_kibana
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks: [elastic]
    depends_on: [es01]

  es01:
    container_name: es01
    environment:
      - xpack.security.enabled=false
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    ports: ["${VNA_ES_PORT}:9200"]
    volumes: ["${VNA_ES_DATA_PATH_ON_HOST}/single_node:/usr/share/elasticsearch/data:rw"]

    image: ${VNA_ES_IMAGE}
    ulimits: { memlock: { soft: -1, hard: -1 } }
    networks: [elastic]

networks:
  elastic:
    driver: bridge
