[package]
name = "vna_migrations"
version = "0.1.0"
authors = ["veetaha <veetaha2@gmail.com>"]
edition = "2018"
publish = false
license = "MIT"

[dependencies]
anyhow = "1.0.31"
log = "0.4.8"
env_logger = "0.7.1"
elasticsearch = "7.7.0-alpha.1"
serde = "1.0.110"
