name: rustdoc
on:
  push:
    branches: [master]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

env:
  # Nightly, because of the feature of namespaces as markdown links.
  # Feel free to upgrade this to a newer nightly, just make sure
  # `cargo +nightly-XXX docs --workspace` compiles without any errors
  RUST_DOC_TOOLCHAIN: nightly-2020-03-26

jobs:
  rustdoc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ env.RUST_DOC_TOOLCHAIN }}
        profile: minimal
        override: true

    - run: cargo +${{ env.RUST_DOC_TOOLCHAIN }} doc --workspace --no-deps

    - name: Deploy Docs
      # taken from https://github.com/rust-analyzer/rust-analyzer/blob/ba51b7b04588cea07ab2cccd1c5f676c8546cb57/.github/workflows/rustdoc.yaml#L33
      # for some reason latest version of this action doesn't work?...
      uses: peaceiris/actions-gh-pages@364c31d33bb99327c77b3a5438a83a357a6729ad # v3.4.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
        force_orphan: true
