[package]
name = "vna_es_utils"
version = "0.1.0"
authors = ["veetaha <veetaha2@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
elasticsearch = "7.7.0-alpha.1"
url = "2.1"
backtrace = "0.3.48"
